ARG BASE_IMG=rust   # default image
ARG BASE_TAG=alpine # default tag
FROM ${BASE_IMG}:${BASE_TAG}

LABEL maintainer "sksat <sksat@sksat.net>"

# depName=LukeMathWalker/cargo-chef datasource=github-releases
ARG CARGO_CHEF_VERSION="v0.1.37"

RUN apk add --no-cache musl-dev=1.2.2-r7 --repository="http://dl-cdn.alpinelinux.org/alpine/v3.14/main"
RUN cargo install --version "${CARGO_CHEF_VERSION#v}" --locked cargo-chef \
  && rm -rf "${CARGO_HOME}"/registry/
