name: 'action-docker-alias'
description: 'GitHub Actions for set docker container image alias'

author: '@sksat'

inputs:
  image:
    description: 'original docker container image'
    required: true
  push:
    description: 'push flag'
    required: true
    default: false
  tags:
    description: 'alias tags'
  tags_json:
    description: 'alias tags in docker/metadata-action json format'

runs:
  using: "composite"
  steps:
    - name: set alias
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
        TAGS: ${{ inputs.tags }}
      run: |
        echo "$TAGS" > tags.lst

    - name: set alias from json
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
        TAGS_JSON: ${{ inputs.tags_json }}
      run: |
        echo "$TAGS_JSON" | jq -r '.tags[]' >> tags.lst

    - name: show tags
      shell: bash
      run: cat tags.lst

    - name: set alias tags & push images
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
      run: |
        for tag in `cat tags.lst`; do
          docker tag "$IMAGE" "$tag"
          if ${{ inputs.push }}; then
            docker push "$tag"
          fi
        done
