name: Build Container Image

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths:
      - 'rust-toolchain'
      - 'Dockerfile'
      - '.github/workflows/build-image.yml'

jobs:
  rust_version:
    runs-on: ubuntu-latest

    outputs:
      rust_version: ${{ steps.rust_ver.outputs.rust_version }}

    steps:
    - uses: actions/checkout@v3
    - name: Get Rust version
      id: rust_ver
      run: |
        echo ::set-output name=rust_version::$(awk -F'[ ="]+' '$1 == "channel" { print $2 }' rust-toolchain)
        echo ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

  build_and_push:
    name: Build and Push
    needs: rust_version
    strategy:
      fail-fast: false
      matrix:
        base_img: [buster, slim-buster, slim, bullseye, slim-bullseye, alpine]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository }},sksat/${{ github.event.repository.name }}
        flavor: |
          latest=auto
          suffix=-${{ needs.rust_version.outputs.rust_version }}-${{ matrix.base_img }}

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ghcr.io
      uses: docker/login-action@v1
      if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      with:
        username: sksat
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set Tag
      id: tags
      run: |
        TAGS_META=$(cat <<EOF
        ${{ steps.meta.outputs.tags }}
        EOF
        )
        echo "tags from meta: ${TAGS_META}"
        TAGS="${TAGS_META}"
        if ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}; then
          echo "add remove default branch version tags"
          for t in ${TAGS_META}; do
            TAGS=$(echo -e "${TAGS}\n$(echo $t | sed 's/${{ github.event.repository.default_branch }}-//')")
          done
        fi
        echo "tags: ${TAGS}"

        TAGS="${TAGS//'%'/'%25'}"
        TAGS="${TAGS//$'\n'/'%0A'}"
        TAGS="${TAGS//$'\r'/'%0D'}"
        echo "::set-output name=tags::${TAGS}"

    - name: Build and Push
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        build-args: BASE_IMG=rust:${{ matrix.base_img }}
        tags: ${{ steps.tags.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha,scope=${{ matrix.base_img }}
        cache-to: type=gha,scope=${{ matrix.base_img }},mode=max
